name: Update README on Push or Pull Request

on:
  push:
    branches:
      - master
      - t

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Check File Names
        env:
          CHANGED_FILES: $(git diff --name-only HEAD~1 HEAD)
        run: |
          echo "$CHANGED_FILES"
          for file in $CHANGED_FILES; do
            echo "$file"
            if [[ ! ($file =~ ^\d+[A-Z]\.(cpp|py)$) ]]; then
              echo "Error: File '$file' does not match allowed pattern"
              exit 1
            fi
          done

      # - name: Run Python script to update README
      #   run: python update_readme.py ${{ steps.verify-changes.outputs.changed_files }}

      # - name: Commit changes
      #   run: |
      #     git config --local user.email "actions@github.com"
      #     git config --local user.name "GitHub Actions"
      #     git add README.md
      #     git commit -m "Update README"

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.CODEFORCES_GITHUB_TOKEN }}
